name: 'Nuxt Nightly'
description: 'An action to test a repository against the latest nightly build of Nuxt'
author: 'Daniel Roe'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'moon'
  color: 'black'

inputs:
  base:
    description: The base branch to raise the PR against.
    required: false
  head:
    description: The name of the branch to create with the changes.
    default: ci/nuxt-nightly
  root:
    description: The directory containing your Nuxt project.
    default: .

runs:
  using: node20
  main: dist/index.js
