name: 'Nuxt Nightly'
description: 'An action to test a repository against the latest nightly build of Nuxt'
author: 'Daniel Roe'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'moon'
  color: 'black'

inputs:
  base:
    required: false
  head:
    default: ci/nuxt-nightly

runs:
  using: node20
  main: dist/index.js
